package markdown

import (
	"bytes"
	"fmt"
	"html/template"

	"github.com/yuin/goldmark/ast"
)

// extractTOC walks the AST to generate a flat HTML list for the Table of Contents.
// It uses CSS classes (e.g., .toc-level-2) to handle indentation instead of nested <ul>s.
func extractTOC(doc ast.Node, source []byte) template.HTML {
	var listBuf bytes.Buffer
	hasHeadings := false

	ast.Walk(doc, func(n ast.Node, entering bool) (ast.WalkStatus, error) {
		// Only process headings on entry
		if !entering || n.Kind() != ast.KindHeading {
			return ast.WalkContinue, nil
		}

		h := n.(*ast.Heading)

		// Extract HTML ID (generated by Goldmark auto-id)
		var id string
		if val, ok := h.Attribute([]byte("id")); ok {
			if idBytes, ok := val.([]byte); ok {
				id = string(idBytes)
			}
		}

		text := string(h.Text(source))

		// Render list item with level-specific class
		listBuf.WriteString(fmt.Sprintf(
			"<li class=\"toc-level-%d\"><a href=\"#%s\">%s</a></li>",
			h.Level, id, text,
		))
		hasHeadings = true

		return ast.WalkContinue, nil
	})

	if !hasHeadings {
		return template.HTML("")
	}

	return template.HTML("<nav class=\"toc\"><ul>" + listBuf.String() + "</ul></nav>")
}
